FROM python:3.9-slim-bullseye

WORKDIR /app

# Instalar dependências system para TPM no Debian
RUN apt-get update && apt-get install -y \
    tpm2-tools \
    tpm2-tss-engine \
    libtss2-esys0 \
    libtss2-mu0 \
    libtss2-tcti-device0 \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Instalar Python packages
RUN pip install --upgrade pip
RUN pip install requests==2.31.0

# Copiar script
COPY vault_initializer.py .

CMD ["python", "vault_initializer.py"]
