services:

  twingate-connector:
    image: twingate/connector:latest
    container_name: twingate-connector
    restart: unless-stopped
    pull_policy: always

    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
      net.ipv6.conf.all.disable_ipv6: 1

    environment:
      TWINGATE_NETWORK: "${TWINGATE_NETWORK}"
      TWINGATE_ACCESS_TOKEN: "${TWINGATE_ACCESS_TOKEN}"
      TWINGATE_REFRESH_TOKEN: "${TWINGATE_REFRESH_TOKEN}"
      TWINGATE_LABEL_HOSTNAME: "${TWINGATE_LABEL_HOSTNAME:-ubuntulocal}"
      TWINGATE_LABEL_DEPLOYED_BY: "docker-compose"
      TWINGATE_TIMESTAMP_FORMAT: "2"
      TWINGATE_LOG_LEVEL: "7"

    labels:
      com.centurylinklabs.watchtower.enable: "true"

    networks:
      - twingate_net

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  twingate-client:
    image: twingate/client:latest
    container_name: twingate-headless-client
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      TWINGATE_LOG_LEVEL: "debug"
      TWINGATE_DNS: "1.1.1.1,8.8.8.8"
    volumes:
      - ./service_key.json:/etc/twingate/service_key.json:ro
    networks: 
      - twingate_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  twingate_net:
    name: twingate-internal-net
    driver: bridge
