services:
  ziti-controller:
    image: openziti/quickstart:latest
    container_name: ziti-controller
    environment:
      - ZITI_CTRL_ADVERTISED_ADDRESS=localhost
      - ZITI_CTRL_PORT=1280
      - ZITI_USER=admin
      - ZITI_PWD=password
    ports:
      - "1280:1280"
      - "8444:8443" # Ziti Admin Console
    networks:
      - ziti-shared-net

  ziti-edge-router:
    image: openziti/quickstart:latest
    container_name: ziti-edge-router
    depends_on:
      - ziti-controller
    environment:
      - ZITI_CTRL_ADVERTISED_ADDRESS=ziti-controller
      - ZITI_CTRL_PORT=1280
    command: /var/openziti/scripts/run-router.sh edge-router
    ports:
      - "3022:3022"
    networks:
      - ziti-shared-net

networks:
  ziti-shared-net:
    external: true
