[registrar]
database_url = sqlite:////var/lib/keylime/reg_data.sqlite

[webapp]
registrar_tls_cert = /var/lib/keylime/reg_cert.pem
registrar_private_key = /var/lib/keylime/reg_private_key.pem

[general]
re_encrypt_hmacs = False
