[verifier]
database_url = sqlite:////var/lib/keylime/verifier_data.sqlite

[webapp]
verifier_tls_cert = /var/lib/keylime/verifier_cert.pem
verifier_private_key = /var/lib/keylime/verifier_private_key.pem

[general]
re_encrypt_hmacs = False
