version: '3.8'

services:
  servidor-iot:
    build: ./servidor
    container_name: servidor_iot_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./servidor:/app
      - ./data/logs:/app/logs
    restart: always
