[verifier]
database_url = sqlite:////var/lib/keylime/verifier_data.sqlite
registrar_ip = localhost
registrar_port = 8891
tls_dir = /var/lib/keylime

[webapp]
verifier_tls_cert = /var/lib/keylime/verifier_cert.pem
verifier_private_key = /var/lib/keylime/verifier_private_key.pem
verifier_port = 8882

[general]
re_encrypt_hmacs = False
