[agent]
ip = "0.0.0.0"
port = 9002
contact_ip = ""
registrar_ip = "localhost"
revocation_notification_ip = "localhost"

[cloud_verifier]
cv_ip = "localhost"
cv_port = 8882

[cloud_node]
enabled = false
