# agent.conf
[agent]
# Define um UUID estático para este agente
uuid = "agent-vault-01" # [12, 36, 37]

# Aponta para o contêiner do registrar na rede 'keylime_public_net'
registrar_ip = "keylime-registrar" # 

# Ouve em todas as interfaces dentro do contêiner
ip = "0.0.0.0" # [20, 36]

# Tamanho do tmpfs seguro para descriptografar o payload
secure_size = "10M" #
